/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { AddressUtils, AddressUtilsInterface } from "../AddressUtils";

const _abi = [
  {
    inputs: [],
    name: "AddressUtils__InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressUtils__NotContract",
    type: "error",
  },
  {
    inputs: [],
    name: "AddressUtils__SendValueFailed",
    type: "error",
  },
] as const;

export class AddressUtils__factory {
  static readonly abi = _abi;
  static createInterface(): AddressUtilsInterface {
    return new Interface(_abi) as AddressUtilsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AddressUtils {
    return new Contract(address, _abi, runner) as unknown as AddressUtils;
  }
}
