/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ArrayUtils, ArrayUtilsInterface } from "../ArrayUtils";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "arrayLength",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "size",
        type: "uint256",
      },
    ],
    name: "ArrayUtils__ArrayCannotExpand",
    type: "error",
  },
] as const;

export class ArrayUtils__factory {
  static readonly abi = _abi;
  static createInterface(): ArrayUtilsInterface {
    return new Interface(_abi) as ArrayUtilsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ArrayUtils {
    return new Contract(address, _abi, runner) as unknown as ArrayUtils;
  }
}
