/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ERC165BaseInternal,
  ERC165BaseInternalInterface,
} from "../ERC165BaseInternal";

const _abi = [
  {
    inputs: [],
    name: "ERC165Base__InvalidInterfaceId",
    type: "error",
  },
] as const;

export class ERC165BaseInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ERC165BaseInternalInterface {
    return new Interface(_abi) as ERC165BaseInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ERC165BaseInternal {
    return new Contract(address, _abi, runner) as unknown as ERC165BaseInternal;
  }
}
