/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IERC20Router, IERC20RouterInterface } from "../IERC20Router";

const _abi = [
  {
    inputs: [],
    name: "ERC20Router__NotAuthorized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Router__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20RouterInterface {
    return new Interface(_abi) as IERC20RouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20Router {
    return new Contract(address, _abi, runner) as unknown as IERC20Router;
  }
}
