/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC165BaseInternal,
  IERC165BaseInternalInterface,
} from "../IERC165BaseInternal";

const _abi = [
  {
    inputs: [],
    name: "ERC165Base__InvalidInterfaceId",
    type: "error",
  },
] as const;

export class IERC165BaseInternal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC165BaseInternalInterface {
    return new Interface(_abi) as IERC165BaseInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC165BaseInternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC165BaseInternal;
  }
}
