/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IERC165Base, IERC165BaseInterface } from "../IERC165Base";

const _abi = [
  {
    inputs: [],
    name: "ERC165Base__InvalidInterfaceId",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC165Base__factory {
  static readonly abi = _abi;
  static createInterface(): IERC165BaseInterface {
    return new Interface(_abi) as IERC165BaseInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC165Base {
    return new Contract(address, _abi, runner) as unknown as IERC165Base;
  }
}
