/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoolFactoryDeployer,
  IPoolFactoryDeployerInterface,
} from "../IPoolFactoryDeployer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "PoolFactoryDeployer__NotPoolFactory",
    type: "error",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "base",
            type: "address",
          },
          {
            internalType: "address",
            name: "quote",
            type: "address",
          },
          {
            internalType: "address",
            name: "oracleAdapter",
            type: "address",
          },
          {
            internalType: "UD60x18",
            name: "strike",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maturity",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isCallPool",
            type: "bool",
          },
        ],
        internalType: "struct IPoolFactory.PoolKey",
        name: "k",
        type: "tuple",
      },
    ],
    name: "calculatePoolAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "base",
            type: "address",
          },
          {
            internalType: "address",
            name: "quote",
            type: "address",
          },
          {
            internalType: "address",
            name: "oracleAdapter",
            type: "address",
          },
          {
            internalType: "UD60x18",
            name: "strike",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maturity",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isCallPool",
            type: "bool",
          },
        ],
        internalType: "struct IPoolFactory.PoolKey",
        name: "k",
        type: "tuple",
      },
    ],
    name: "deployPool",
    outputs: [
      {
        internalType: "address",
        name: "poolAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoolFactoryDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolFactoryDeployerInterface {
    return new Interface(_abi) as IPoolFactoryDeployerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPoolFactoryDeployer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPoolFactoryDeployer;
  }
}
