/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReentrancyGuard,
  IReentrancyGuardInterface,
} from "../IReentrancyGuard";

const _abi = [
  {
    inputs: [],
    name: "ReentrancyGuard__ReentrantCall",
    type: "error",
  },
] as const;

export class IReentrancyGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IReentrancyGuardInterface {
    return new Interface(_abi) as IReentrancyGuardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReentrancyGuard {
    return new Contract(address, _abi, runner) as unknown as IReentrancyGuard;
  }
}
