/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Placeholder, PlaceholderInterface } from "../Placeholder";

const _abi = [
  {
    inputs: [],
    name: "placeholder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Placeholder__factory {
  static readonly abi = _abi;
  static createInterface(): PlaceholderInterface {
    return new Interface(_abi) as PlaceholderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Placeholder {
    return new Contract(address, _abi, runner) as unknown as Placeholder;
  }
}
