/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { TickMath, TickMathInterface } from "../TickMath";

const _abi = [
  {
    inputs: [],
    name: "R",
    type: "error",
  },
  {
    inputs: [],
    name: "T",
    type: "error",
  },
] as const;

export class TickMath__factory {
  static readonly abi = _abi;
  static createInterface(): TickMathInterface {
    return new Interface(_abi) as TickMathInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TickMath {
    return new Contract(address, _abi, runner) as unknown as TickMath;
  }
}
