/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VxPremiaStorage {
  export type VoteStruct = {
    amount: BigNumberish;
    version: BigNumberish;
    target: BytesLike;
  };

  export type VoteStructOutput = [
    amount: bigint,
    version: bigint,
    target: string
  ] & { amount: bigint; version: bigint; target: string };
}

export declare namespace IPremiaStaking {
  export type StakeLevelStruct = {
    amount: BigNumberish;
    discount: BigNumberish;
  };

  export type StakeLevelStructOutput = [amount: bigint, discount: bigint] & {
    amount: bigint;
    discount: bigint;
  };

  export type SwapArgsStruct = {
    amountOutMin: BigNumberish;
    callee: AddressLike;
    allowanceTarget: AddressLike;
    data: BytesLike;
    refundAddress: AddressLike;
  };

  export type SwapArgsStructOutput = [
    amountOutMin: bigint,
    callee: string,
    allowanceTarget: string,
    data: string,
    refundAddress: string
  ] & {
    amountOutMin: bigint;
    callee: string;
    allowanceTarget: string;
    data: string;
    refundAddress: string;
  };
}

export declare namespace PremiaStakingStorage {
  export type UserInfoStruct = {
    reward: BigNumberish;
    rewardDebt: BigNumberish;
    unstakeRewardDebt: BigNumberish;
    stakePeriod: BigNumberish;
    lockedUntil: BigNumberish;
  };

  export type UserInfoStructOutput = [
    reward: bigint,
    rewardDebt: bigint,
    unstakeRewardDebt: bigint,
    stakePeriod: bigint,
    lockedUntil: bigint
  ] & {
    reward: bigint;
    rewardDebt: bigint;
    unstakeRewardDebt: bigint;
    stakePeriod: bigint;
    lockedUntil: bigint;
  };
}

export interface IVxPremiaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR"
      | "addRewards"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "castVotes"
      | "circulatingSupply"
      | "decimals"
      | "decreaseAllowance"
      | "earlyUnstake"
      | "estimateSendFee"
      | "getAvailablePremiaAmount"
      | "getAvailableRewards"
      | "getDiscount"
      | "getEarlyUnstakeFee"
      | "getPendingRewards"
      | "getPendingUserRewards"
      | "getPendingWithdrawal"
      | "getPendingWithdrawals"
      | "getPoolVotes"
      | "getRewardToken"
      | "getStakeLevels"
      | "getStakePeriodMultiplier"
      | "getTotalPower"
      | "getUserInfo"
      | "getUserPower"
      | "getUserVotes"
      | "harvest"
      | "harvestAndStake"
      | "increaseAllowance"
      | "name"
      | "nonces"
      | "permit"
      | "sendFrom"
      | "stake"
      | "stakeWithPermit"
      | "startWithdraw"
      | "supportsInterface"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "updateLock"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddVote"
      | "Approval"
      | "BridgeLock"
      | "EarlyUnstakeRewardCollected"
      | "Harvest"
      | "ReceiveFromChain"
      | "RemoveVote"
      | "RewardsAdded"
      | "SendToChain"
      | "SetUseCustomAdapterParams"
      | "Stake"
      | "Transfer"
      | "Unstake"
      | "UpdateLock"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "castVotes",
    values: [VxPremiaStorage.VoteStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "circulatingSupply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyUnstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateSendFee",
    values: [BigNumberish, BytesLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailablePremiaAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDiscount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEarlyUnstakeFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingUserRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingWithdrawal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingWithdrawals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolVotes",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeLevels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakePeriodMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "harvest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "harvestAndStake",
    values: [IPremiaStaking.SwapArgsStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendFrom",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeWithPermit",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "startWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "castVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "circulatingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earlyUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateSendFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailablePremiaAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEarlyUnstakeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingUserRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakePeriodMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "harvest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestAndStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendFrom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateLock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AddVoteEvent {
  export type InputTuple = [
    voter: AddressLike,
    version: BigNumberish,
    target: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    version: bigint,
    target: string,
    amount: bigint
  ];
  export interface OutputObject {
    voter: string;
    version: bigint;
    target: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeLockEvent {
  export type InputTuple = [
    user: AddressLike,
    stakePeriod: BigNumberish,
    lockedUntil: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    stakePeriod: bigint,
    lockedUntil: bigint
  ];
  export interface OutputObject {
    user: string;
    stakePeriod: bigint;
    lockedUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarlyUnstakeRewardCollectedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiveFromChainEvent {
  export type InputTuple = [
    srcChainId: BigNumberish,
    srcAddress: BytesLike,
    toAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    srcChainId: bigint,
    srcAddress: string,
    toAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    srcChainId: bigint;
    srcAddress: string;
    toAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveVoteEvent {
  export type InputTuple = [
    voter: AddressLike,
    version: BigNumberish,
    target: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    version: bigint,
    target: string,
    amount: bigint
  ];
  export interface OutputObject {
    voter: string;
    version: bigint;
    target: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsAddedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SendToChainEvent {
  export type InputTuple = [
    sender: AddressLike,
    dstChainId: BigNumberish,
    toAddress: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    dstChainId: bigint,
    toAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    sender: string;
    dstChainId: bigint;
    toAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetUseCustomAdapterParamsEvent {
  export type InputTuple = [_useCustomAdapterParams: boolean];
  export type OutputTuple = [_useCustomAdapterParams: boolean];
  export interface OutputObject {
    _useCustomAdapterParams: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    stakePeriod: BigNumberish,
    lockedUntil: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    stakePeriod: bigint,
    lockedUntil: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    stakePeriod: bigint;
    lockedUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakeEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    startDate: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    fee: bigint,
    startDate: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
    startDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateLockEvent {
  export type InputTuple = [
    user: AddressLike,
    oldStakePeriod: BigNumberish,
    newStakePeriod: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    oldStakePeriod: bigint,
    newStakePeriod: bigint
  ];
  export interface OutputObject {
    user: string;
    oldStakePeriod: bigint;
    newStakePeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IVxPremia extends BaseContract {
  connect(runner?: ContractRunner | null): IVxPremia;
  waitForDeployment(): Promise<this>;

  interface: IVxPremiaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  addRewards: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  allowance: TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  castVotes: TypedContractMethod<
    [votes: VxPremiaStorage.VoteStruct[]],
    [void],
    "nonpayable"
  >;

  circulatingSupply: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  earlyUnstake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  estimateSendFee: TypedContractMethod<
    [
      dstChainId: BigNumberish,
      toAddress: BytesLike,
      amount: BigNumberish,
      useZro: boolean,
      adapterParams: BytesLike
    ],
    [[bigint, bigint] & { nativeFee: bigint; zroFee: bigint }],
    "view"
  >;

  getAvailablePremiaAmount: TypedContractMethod<[], [bigint], "view">;

  getAvailableRewards: TypedContractMethod<
    [],
    [[bigint, bigint] & { rewards: bigint; unstakeRewards: bigint }],
    "view"
  >;

  getDiscount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEarlyUnstakeFee: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getPendingRewards: TypedContractMethod<[], [bigint], "view">;

  getPendingUserRewards: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { reward: bigint; unstakeReward: bigint }],
    "view"
  >;

  getPendingWithdrawal: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        startDate: bigint;
        unlockDate: bigint;
      }
    ],
    "view"
  >;

  getPendingWithdrawals: TypedContractMethod<[], [bigint], "view">;

  getPoolVotes: TypedContractMethod<
    [version: BigNumberish, target: BytesLike],
    [bigint],
    "view"
  >;

  getRewardToken: TypedContractMethod<[], [string], "view">;

  getStakeLevels: TypedContractMethod<
    [],
    [IPremiaStaking.StakeLevelStructOutput[]],
    "view"
  >;

  getStakePeriodMultiplier: TypedContractMethod<
    [period: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalPower: TypedContractMethod<[], [bigint], "view">;

  getUserInfo: TypedContractMethod<
    [user: AddressLike],
    [PremiaStakingStorage.UserInfoStructOutput],
    "view"
  >;

  getUserPower: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserVotes: TypedContractMethod<
    [user: AddressLike],
    [VxPremiaStorage.VoteStructOutput[]],
    "view"
  >;

  harvest: TypedContractMethod<[], [void], "nonpayable">;

  harvestAndStake: TypedContractMethod<
    [s: IPremiaStaking.SwapArgsStruct, stakePeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  permit: TypedContractMethod<
    [
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  sendFrom: TypedContractMethod<
    [
      from: AddressLike,
      dstChainId: BigNumberish,
      toAddress: BytesLike,
      amount: BigNumberish,
      refundAddress: AddressLike,
      zroPaymentAddress: AddressLike,
      adapterParams: BytesLike
    ],
    [void],
    "payable"
  >;

  stake: TypedContractMethod<
    [amount: BigNumberish, period: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeWithPermit: TypedContractMethod<
    [
      amount: BigNumberish,
      period: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  startWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [holder: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  updateLock: TypedContractMethod<[period: BigNumberish], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRewards"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "castVotes"
  ): TypedContractMethod<
    [votes: VxPremiaStorage.VoteStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "circulatingSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "earlyUnstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "estimateSendFee"
  ): TypedContractMethod<
    [
      dstChainId: BigNumberish,
      toAddress: BytesLike,
      amount: BigNumberish,
      useZro: boolean,
      adapterParams: BytesLike
    ],
    [[bigint, bigint] & { nativeFee: bigint; zroFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAvailablePremiaAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableRewards"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { rewards: bigint; unstakeRewards: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDiscount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEarlyUnstakeFee"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingUserRewards"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { reward: bigint; unstakeReward: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingWithdrawal"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        startDate: bigint;
        unlockDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingWithdrawals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolVotes"
  ): TypedContractMethod<
    [version: BigNumberish, target: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStakeLevels"
  ): TypedContractMethod<[], [IPremiaStaking.StakeLevelStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getStakePeriodMultiplier"
  ): TypedContractMethod<[period: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalPower"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [PremiaStakingStorage.UserInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPower"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserVotes"
  ): TypedContractMethod<
    [user: AddressLike],
    [VxPremiaStorage.VoteStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "harvest"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "harvestAndStake"
  ): TypedContractMethod<
    [s: IPremiaStaking.SwapArgsStruct, stakePeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "permit"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      dstChainId: BigNumberish,
      toAddress: BytesLike,
      amount: BigNumberish,
      refundAddress: AddressLike,
      zroPaymentAddress: AddressLike,
      adapterParams: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [amount: BigNumberish, period: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeWithPermit"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      period: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [holder: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLock"
  ): TypedContractMethod<[period: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AddVote"
  ): TypedContractEvent<
    AddVoteEvent.InputTuple,
    AddVoteEvent.OutputTuple,
    AddVoteEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BridgeLock"
  ): TypedContractEvent<
    BridgeLockEvent.InputTuple,
    BridgeLockEvent.OutputTuple,
    BridgeLockEvent.OutputObject
  >;
  getEvent(
    key: "EarlyUnstakeRewardCollected"
  ): TypedContractEvent<
    EarlyUnstakeRewardCollectedEvent.InputTuple,
    EarlyUnstakeRewardCollectedEvent.OutputTuple,
    EarlyUnstakeRewardCollectedEvent.OutputObject
  >;
  getEvent(
    key: "Harvest"
  ): TypedContractEvent<
    HarvestEvent.InputTuple,
    HarvestEvent.OutputTuple,
    HarvestEvent.OutputObject
  >;
  getEvent(
    key: "ReceiveFromChain"
  ): TypedContractEvent<
    ReceiveFromChainEvent.InputTuple,
    ReceiveFromChainEvent.OutputTuple,
    ReceiveFromChainEvent.OutputObject
  >;
  getEvent(
    key: "RemoveVote"
  ): TypedContractEvent<
    RemoveVoteEvent.InputTuple,
    RemoveVoteEvent.OutputTuple,
    RemoveVoteEvent.OutputObject
  >;
  getEvent(
    key: "RewardsAdded"
  ): TypedContractEvent<
    RewardsAddedEvent.InputTuple,
    RewardsAddedEvent.OutputTuple,
    RewardsAddedEvent.OutputObject
  >;
  getEvent(
    key: "SendToChain"
  ): TypedContractEvent<
    SendToChainEvent.InputTuple,
    SendToChainEvent.OutputTuple,
    SendToChainEvent.OutputObject
  >;
  getEvent(
    key: "SetUseCustomAdapterParams"
  ): TypedContractEvent<
    SetUseCustomAdapterParamsEvent.InputTuple,
    SetUseCustomAdapterParamsEvent.OutputTuple,
    SetUseCustomAdapterParamsEvent.OutputObject
  >;
  getEvent(
    key: "Stake"
  ): TypedContractEvent<
    StakeEvent.InputTuple,
    StakeEvent.OutputTuple,
    StakeEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unstake"
  ): TypedContractEvent<
    UnstakeEvent.InputTuple,
    UnstakeEvent.OutputTuple,
    UnstakeEvent.OutputObject
  >;
  getEvent(
    key: "UpdateLock"
  ): TypedContractEvent<
    UpdateLockEvent.InputTuple,
    UpdateLockEvent.OutputTuple,
    UpdateLockEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "AddVote(address,uint8,bytes,uint256)": TypedContractEvent<
      AddVoteEvent.InputTuple,
      AddVoteEvent.OutputTuple,
      AddVoteEvent.OutputObject
    >;
    AddVote: TypedContractEvent<
      AddVoteEvent.InputTuple,
      AddVoteEvent.OutputTuple,
      AddVoteEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BridgeLock(address,uint64,uint64)": TypedContractEvent<
      BridgeLockEvent.InputTuple,
      BridgeLockEvent.OutputTuple,
      BridgeLockEvent.OutputObject
    >;
    BridgeLock: TypedContractEvent<
      BridgeLockEvent.InputTuple,
      BridgeLockEvent.OutputTuple,
      BridgeLockEvent.OutputObject
    >;

    "EarlyUnstakeRewardCollected(address,uint256)": TypedContractEvent<
      EarlyUnstakeRewardCollectedEvent.InputTuple,
      EarlyUnstakeRewardCollectedEvent.OutputTuple,
      EarlyUnstakeRewardCollectedEvent.OutputObject
    >;
    EarlyUnstakeRewardCollected: TypedContractEvent<
      EarlyUnstakeRewardCollectedEvent.InputTuple,
      EarlyUnstakeRewardCollectedEvent.OutputTuple,
      EarlyUnstakeRewardCollectedEvent.OutputObject
    >;

    "Harvest(address,uint256)": TypedContractEvent<
      HarvestEvent.InputTuple,
      HarvestEvent.OutputTuple,
      HarvestEvent.OutputObject
    >;
    Harvest: TypedContractEvent<
      HarvestEvent.InputTuple,
      HarvestEvent.OutputTuple,
      HarvestEvent.OutputObject
    >;

    "ReceiveFromChain(uint16,bytes,address,uint256)": TypedContractEvent<
      ReceiveFromChainEvent.InputTuple,
      ReceiveFromChainEvent.OutputTuple,
      ReceiveFromChainEvent.OutputObject
    >;
    ReceiveFromChain: TypedContractEvent<
      ReceiveFromChainEvent.InputTuple,
      ReceiveFromChainEvent.OutputTuple,
      ReceiveFromChainEvent.OutputObject
    >;

    "RemoveVote(address,uint8,bytes,uint256)": TypedContractEvent<
      RemoveVoteEvent.InputTuple,
      RemoveVoteEvent.OutputTuple,
      RemoveVoteEvent.OutputObject
    >;
    RemoveVote: TypedContractEvent<
      RemoveVoteEvent.InputTuple,
      RemoveVoteEvent.OutputTuple,
      RemoveVoteEvent.OutputObject
    >;

    "RewardsAdded(uint256)": TypedContractEvent<
      RewardsAddedEvent.InputTuple,
      RewardsAddedEvent.OutputTuple,
      RewardsAddedEvent.OutputObject
    >;
    RewardsAdded: TypedContractEvent<
      RewardsAddedEvent.InputTuple,
      RewardsAddedEvent.OutputTuple,
      RewardsAddedEvent.OutputObject
    >;

    "SendToChain(address,uint16,bytes,uint256)": TypedContractEvent<
      SendToChainEvent.InputTuple,
      SendToChainEvent.OutputTuple,
      SendToChainEvent.OutputObject
    >;
    SendToChain: TypedContractEvent<
      SendToChainEvent.InputTuple,
      SendToChainEvent.OutputTuple,
      SendToChainEvent.OutputObject
    >;

    "SetUseCustomAdapterParams(bool)": TypedContractEvent<
      SetUseCustomAdapterParamsEvent.InputTuple,
      SetUseCustomAdapterParamsEvent.OutputTuple,
      SetUseCustomAdapterParamsEvent.OutputObject
    >;
    SetUseCustomAdapterParams: TypedContractEvent<
      SetUseCustomAdapterParamsEvent.InputTuple,
      SetUseCustomAdapterParamsEvent.OutputTuple,
      SetUseCustomAdapterParamsEvent.OutputObject
    >;

    "Stake(address,uint256,uint64,uint64)": TypedContractEvent<
      StakeEvent.InputTuple,
      StakeEvent.OutputTuple,
      StakeEvent.OutputObject
    >;
    Stake: TypedContractEvent<
      StakeEvent.InputTuple,
      StakeEvent.OutputTuple,
      StakeEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unstake(address,uint256,uint256,uint256)": TypedContractEvent<
      UnstakeEvent.InputTuple,
      UnstakeEvent.OutputTuple,
      UnstakeEvent.OutputObject
    >;
    Unstake: TypedContractEvent<
      UnstakeEvent.InputTuple,
      UnstakeEvent.OutputTuple,
      UnstakeEvent.OutputObject
    >;

    "UpdateLock(address,uint64,uint64)": TypedContractEvent<
      UpdateLockEvent.InputTuple,
      UpdateLockEvent.OutputTuple,
      UpdateLockEvent.OutputObject
    >;
    UpdateLock: TypedContractEvent<
      UpdateLockEvent.InputTuple,
      UpdateLockEvent.OutputTuple,
      UpdateLockEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
