/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface OptionMathExternalInterface extends Interface {
  getFunction(
    nameOrSignature: "blackScholesPrice" | "optionDelta"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "blackScholesPrice",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "optionDelta",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "blackScholesPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionDelta",
    data: BytesLike
  ): Result;
}

export interface OptionMathExternal extends BaseContract {
  connect(runner?: ContractRunner | null): OptionMathExternal;
  waitForDeployment(): Promise<this>;

  interface: OptionMathExternalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blackScholesPrice: TypedContractMethod<
    [
      spot: BigNumberish,
      strike: BigNumberish,
      timeToMaturity: BigNumberish,
      volAnnualized: BigNumberish,
      riskFreeRate: BigNumberish,
      isCall: boolean
    ],
    [bigint],
    "view"
  >;

  optionDelta: TypedContractMethod<
    [
      spot: BigNumberish,
      strike: BigNumberish,
      timeToMaturity: BigNumberish,
      volAnnualized: BigNumberish,
      riskFreeRate: BigNumberish,
      isCall: boolean
    ],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blackScholesPrice"
  ): TypedContractMethod<
    [
      spot: BigNumberish,
      strike: BigNumberish,
      timeToMaturity: BigNumberish,
      volAnnualized: BigNumberish,
      riskFreeRate: BigNumberish,
      isCall: boolean
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "optionDelta"
  ): TypedContractMethod<
    [
      spot: BigNumberish,
      strike: BigNumberish,
      timeToMaturity: BigNumberish,
      volAnnualized: BigNumberish,
      riskFreeRate: BigNumberish,
      isCall: boolean
    ],
    [bigint],
    "view"
  >;

  filters: {};
}
