/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PoolFactoryProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "getImplementation"
      | "nomineeOwner"
      | "owner"
      | "setImplementation"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ImplementationSet"
      | "OwnershipTransferred"
      | "PoolDeployed"
      | "PricingPath"
      | "SetDiscountPerPool"
      | "SetFeeReceiver"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nomineeOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nomineeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ImplementationSetEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolDeployedEvent {
  export type InputTuple = [
    base: AddressLike,
    quote: AddressLike,
    oracleAdapter: AddressLike,
    strike: BigNumberish,
    maturity: BigNumberish,
    isCallPool: boolean,
    poolAddress: AddressLike
  ];
  export type OutputTuple = [
    base: string,
    quote: string,
    oracleAdapter: string,
    strike: bigint,
    maturity: bigint,
    isCallPool: boolean,
    poolAddress: string
  ];
  export interface OutputObject {
    base: string;
    quote: string;
    oracleAdapter: string;
    strike: bigint;
    maturity: bigint;
    isCallPool: boolean;
    poolAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PricingPathEvent {
  export type InputTuple = [
    pool: AddressLike,
    basePath: AddressLike[][],
    basePathDecimals: BigNumberish[],
    baseAdapterType: BigNumberish,
    quotePath: AddressLike[][],
    quotePathDecimals: BigNumberish[],
    quoteAdapterType: BigNumberish
  ];
  export type OutputTuple = [
    pool: string,
    basePath: string[][],
    basePathDecimals: bigint[],
    baseAdapterType: bigint,
    quotePath: string[][],
    quotePathDecimals: bigint[],
    quoteAdapterType: bigint
  ];
  export interface OutputObject {
    pool: string;
    basePath: string[][];
    basePathDecimals: bigint[];
    baseAdapterType: bigint;
    quotePath: string[][];
    quotePathDecimals: bigint[];
    quoteAdapterType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetDiscountPerPoolEvent {
  export type InputTuple = [discountPerPool: BigNumberish];
  export type OutputTuple = [discountPerPool: bigint];
  export interface OutputObject {
    discountPerPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetFeeReceiverEvent {
  export type InputTuple = [feeReceiver: AddressLike];
  export type OutputTuple = [feeReceiver: string];
  export interface OutputObject {
    feeReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoolFactoryProxy extends BaseContract {
  connect(runner?: ContractRunner | null): PoolFactoryProxy;
  waitForDeployment(): Promise<this>;

  interface: PoolFactoryProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  getImplementation: TypedContractMethod<[], [string], "view">;

  nomineeOwner: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setImplementation: TypedContractMethod<
    [implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nomineeOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setImplementation"
  ): TypedContractMethod<[implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ImplementationSet"
  ): TypedContractEvent<
    ImplementationSetEvent.InputTuple,
    ImplementationSetEvent.OutputTuple,
    ImplementationSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolDeployed"
  ): TypedContractEvent<
    PoolDeployedEvent.InputTuple,
    PoolDeployedEvent.OutputTuple,
    PoolDeployedEvent.OutputObject
  >;
  getEvent(
    key: "PricingPath"
  ): TypedContractEvent<
    PricingPathEvent.InputTuple,
    PricingPathEvent.OutputTuple,
    PricingPathEvent.OutputObject
  >;
  getEvent(
    key: "SetDiscountPerPool"
  ): TypedContractEvent<
    SetDiscountPerPoolEvent.InputTuple,
    SetDiscountPerPoolEvent.OutputTuple,
    SetDiscountPerPoolEvent.OutputObject
  >;
  getEvent(
    key: "SetFeeReceiver"
  ): TypedContractEvent<
    SetFeeReceiverEvent.InputTuple,
    SetFeeReceiverEvent.OutputTuple,
    SetFeeReceiverEvent.OutputObject
  >;

  filters: {
    "ImplementationSet(address)": TypedContractEvent<
      ImplementationSetEvent.InputTuple,
      ImplementationSetEvent.OutputTuple,
      ImplementationSetEvent.OutputObject
    >;
    ImplementationSet: TypedContractEvent<
      ImplementationSetEvent.InputTuple,
      ImplementationSetEvent.OutputTuple,
      ImplementationSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolDeployed(address,address,address,uint256,uint256,bool,address)": TypedContractEvent<
      PoolDeployedEvent.InputTuple,
      PoolDeployedEvent.OutputTuple,
      PoolDeployedEvent.OutputObject
    >;
    PoolDeployed: TypedContractEvent<
      PoolDeployedEvent.InputTuple,
      PoolDeployedEvent.OutputTuple,
      PoolDeployedEvent.OutputObject
    >;

    "PricingPath(address,address[][],uint8[],uint8,address[][],uint8[],uint8)": TypedContractEvent<
      PricingPathEvent.InputTuple,
      PricingPathEvent.OutputTuple,
      PricingPathEvent.OutputObject
    >;
    PricingPath: TypedContractEvent<
      PricingPathEvent.InputTuple,
      PricingPathEvent.OutputTuple,
      PricingPathEvent.OutputObject
    >;

    "SetDiscountPerPool(uint256)": TypedContractEvent<
      SetDiscountPerPoolEvent.InputTuple,
      SetDiscountPerPoolEvent.OutputTuple,
      SetDiscountPerPoolEvent.OutputObject
    >;
    SetDiscountPerPool: TypedContractEvent<
      SetDiscountPerPoolEvent.InputTuple,
      SetDiscountPerPoolEvent.OutputTuple,
      SetDiscountPerPoolEvent.OutputObject
    >;

    "SetFeeReceiver(address)": TypedContractEvent<
      SetFeeReceiverEvent.InputTuple,
      SetFeeReceiverEvent.OutputTuple,
      SetFeeReceiverEvent.OutputObject
    >;
    SetFeeReceiver: TypedContractEvent<
      SetFeeReceiverEvent.InputTuple,
      SetFeeReceiverEvent.OutputTuple,
      SetFeeReceiverEvent.OutputObject
    >;
  };
}
