/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Position {
  export type DeltaStruct = {
    collateral: BigNumberish;
    longs: BigNumberish;
    shorts: BigNumberish;
  };

  export type DeltaStructOutput = [
    collateral: bigint,
    longs: bigint,
    shorts: bigint
  ] & { collateral: bigint; longs: bigint; shorts: bigint };

  export type KeyStruct = {
    owner: AddressLike;
    operator: AddressLike;
    lower: BigNumberish;
    upper: BigNumberish;
    orderType: BigNumberish;
  };

  export type KeyStructOutput = [
    owner: string,
    operator: string,
    lower: bigint,
    upper: bigint,
    orderType: bigint
  ] & {
    owner: string;
    operator: string;
    lower: bigint;
    upper: bigint;
    orderType: bigint;
  };
}

export declare namespace IPoolInternal {
  export type TickStruct = {
    delta: BigNumberish;
    externalFeeRate: BigNumberish;
    longDelta: BigNumberish;
    shortDelta: BigNumberish;
    counter: BigNumberish;
  };

  export type TickStructOutput = [
    delta: bigint,
    externalFeeRate: bigint,
    longDelta: bigint,
    shortDelta: bigint,
    counter: bigint
  ] & {
    delta: bigint;
    externalFeeRate: bigint;
    longDelta: bigint;
    shortDelta: bigint;
    counter: bigint;
  };

  export type TickWithRatesStruct = {
    tick: IPoolInternal.TickStruct;
    price: BigNumberish;
    longRate: BigNumberish;
    shortRate: BigNumberish;
  };

  export type TickWithRatesStructOutput = [
    tick: IPoolInternal.TickStructOutput,
    price: bigint,
    longRate: bigint,
    shortRate: bigint
  ] & {
    tick: IPoolInternal.TickStructOutput;
    price: bigint;
    longRate: bigint;
    shortRate: bigint;
  };
}

export interface PoolCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_takerFeeLowLevel"
      | "annihilate"
      | "annihilateFor"
      | "claim"
      | "exercise"
      | "exerciseFor"
      | "getClaimableFees"
      | "getPoolSettings"
      | "getSettlementPrice"
      | "getStrandedArea"
      | "getTokenIds"
      | "marketPrice"
      | "settle"
      | "settleFor"
      | "settlePosition"
      | "settlePositionFor"
      | "takerFee"
      | "ticks"
      | "transferPosition"
      | "writeFrom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Annihilate"
      | "ApprovalForAll"
      | "CancelQuoteOB"
      | "ClaimFees"
      | "ClaimProtocolFees"
      | "Deposit"
      | "Exercise"
      | "FillQuoteOB"
      | "FlashLoan"
      | "Settle"
      | "SettlePosition"
      | "Trade"
      | "TransferBatch"
      | "TransferPosition"
      | "TransferSingle"
      | "UpdateTick"
      | "Withdrawal"
      | "WriteFrom"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_takerFeeLowLevel",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "annihilate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "annihilateFor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [Position.KeyStruct]
  ): string;
  encodeFunctionData(functionFragment: "exercise", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "exerciseFor",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableFees",
    values: [Position.KeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolSettings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlementPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStrandedArea",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "settle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "settleFor",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlePosition",
    values: [Position.KeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "settlePositionFor",
    values: [Position.KeyStruct[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "takerFee",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "ticks", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferPosition",
    values: [Position.KeyStruct, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "writeFrom",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_takerFeeLowLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "annihilate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "annihilateFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exercise", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exerciseFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettlementPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrandedArea",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settleFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlePositionFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "takerFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ticks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "writeFrom", data: BytesLike): Result;
}

export namespace AnnihilateEvent {
  export type InputTuple = [
    owner: AddressLike,
    contractSize: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [owner: string, contractSize: bigint, fee: bigint];
  export interface OutputObject {
    owner: string;
    contractSize: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    account: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    account: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CancelQuoteOBEvent {
  export type InputTuple = [provider: AddressLike, quoteOBHash: BytesLike];
  export type OutputTuple = [provider: string, quoteOBHash: string];
  export interface OutputObject {
    provider: string;
    quoteOBHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimFeesEvent {
  export type InputTuple = [
    owner: AddressLike,
    tokenId: BigNumberish,
    feesClaimed: BigNumberish,
    lastFeeRate: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    tokenId: bigint,
    feesClaimed: bigint,
    lastFeeRate: bigint
  ];
  export interface OutputObject {
    owner: string;
    tokenId: bigint;
    feesClaimed: bigint;
    lastFeeRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimProtocolFeesEvent {
  export type InputTuple = [
    feeReceiver: AddressLike,
    feesClaimed: BigNumberish
  ];
  export type OutputTuple = [feeReceiver: string, feesClaimed: bigint];
  export interface OutputObject {
    feeReceiver: string;
    feesClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    owner: AddressLike,
    tokenId: BigNumberish,
    collateral: BigNumberish,
    longs: BigNumberish,
    shorts: BigNumberish,
    lastFeeRate: BigNumberish,
    claimableFees: BigNumberish,
    marketPrice: BigNumberish,
    liquidityRate: BigNumberish,
    currentTick: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    tokenId: bigint,
    collateral: bigint,
    longs: bigint,
    shorts: bigint,
    lastFeeRate: bigint,
    claimableFees: bigint,
    marketPrice: bigint,
    liquidityRate: bigint,
    currentTick: bigint
  ];
  export interface OutputObject {
    owner: string;
    tokenId: bigint;
    collateral: bigint;
    longs: bigint;
    shorts: bigint;
    lastFeeRate: bigint;
    claimableFees: bigint;
    marketPrice: bigint;
    liquidityRate: bigint;
    currentTick: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExerciseEvent {
  export type InputTuple = [
    operator: AddressLike,
    holder: AddressLike,
    contractSize: BigNumberish,
    exerciseValue: BigNumberish,
    settlementPrice: BigNumberish,
    fee: BigNumberish,
    operatorCost: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    holder: string,
    contractSize: bigint,
    exerciseValue: bigint,
    settlementPrice: bigint,
    fee: bigint,
    operatorCost: bigint
  ];
  export interface OutputObject {
    operator: string;
    holder: string;
    contractSize: bigint;
    exerciseValue: bigint;
    settlementPrice: bigint;
    fee: bigint;
    operatorCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FillQuoteOBEvent {
  export type InputTuple = [
    quoteOBHash: BytesLike,
    user: AddressLike,
    provider: AddressLike,
    contractSize: BigNumberish,
    deltaMaker: Position.DeltaStruct,
    deltaTaker: Position.DeltaStruct,
    premium: BigNumberish,
    protocolFee: BigNumberish,
    totalReferralRebate: BigNumberish,
    isBuy: boolean
  ];
  export type OutputTuple = [
    quoteOBHash: string,
    user: string,
    provider: string,
    contractSize: bigint,
    deltaMaker: Position.DeltaStructOutput,
    deltaTaker: Position.DeltaStructOutput,
    premium: bigint,
    protocolFee: bigint,
    totalReferralRebate: bigint,
    isBuy: boolean
  ];
  export interface OutputObject {
    quoteOBHash: string;
    user: string;
    provider: string;
    contractSize: bigint;
    deltaMaker: Position.DeltaStructOutput;
    deltaTaker: Position.DeltaStructOutput;
    premium: bigint;
    protocolFee: bigint;
    totalReferralRebate: bigint;
    isBuy: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanEvent {
  export type InputTuple = [
    initiator: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    initiator: string,
    receiver: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    initiator: string;
    receiver: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettleEvent {
  export type InputTuple = [
    operator: AddressLike,
    holder: AddressLike,
    contractSize: BigNumberish,
    exerciseValue: BigNumberish,
    settlementPrice: BigNumberish,
    fee: BigNumberish,
    operatorCost: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    holder: string,
    contractSize: bigint,
    exerciseValue: bigint,
    settlementPrice: bigint,
    fee: bigint,
    operatorCost: bigint
  ];
  export interface OutputObject {
    operator: string;
    holder: string;
    contractSize: bigint;
    exerciseValue: bigint;
    settlementPrice: bigint;
    fee: bigint;
    operatorCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlePositionEvent {
  export type InputTuple = [
    operator: AddressLike,
    owner: AddressLike,
    tokenId: BigNumberish,
    contractSize: BigNumberish,
    collateral: BigNumberish,
    exerciseValue: BigNumberish,
    feesClaimed: BigNumberish,
    settlementPrice: BigNumberish,
    fee: BigNumberish,
    operatorCost: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    owner: string,
    tokenId: bigint,
    contractSize: bigint,
    collateral: bigint,
    exerciseValue: bigint,
    feesClaimed: bigint,
    settlementPrice: bigint,
    fee: bigint,
    operatorCost: bigint
  ];
  export interface OutputObject {
    operator: string;
    owner: string;
    tokenId: bigint;
    contractSize: bigint;
    collateral: bigint;
    exerciseValue: bigint;
    feesClaimed: bigint;
    settlementPrice: bigint;
    fee: bigint;
    operatorCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    user: AddressLike,
    contractSize: BigNumberish,
    delta: Position.DeltaStruct,
    premium: BigNumberish,
    takerFee: BigNumberish,
    protocolFee: BigNumberish,
    marketPrice: BigNumberish,
    liquidityRate: BigNumberish,
    currentTick: BigNumberish,
    totalReferralRebate: BigNumberish,
    isBuy: boolean
  ];
  export type OutputTuple = [
    user: string,
    contractSize: bigint,
    delta: Position.DeltaStructOutput,
    premium: bigint,
    takerFee: bigint,
    protocolFee: bigint,
    marketPrice: bigint,
    liquidityRate: bigint,
    currentTick: bigint,
    totalReferralRebate: bigint,
    isBuy: boolean
  ];
  export interface OutputObject {
    user: string;
    contractSize: bigint;
    delta: Position.DeltaStructOutput;
    premium: bigint;
    takerFee: bigint;
    protocolFee: bigint;
    marketPrice: bigint;
    liquidityRate: bigint;
    currentTick: bigint;
    totalReferralRebate: bigint;
    isBuy: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[]
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[]
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferPositionEvent {
  export type InputTuple = [
    owner: AddressLike,
    receiver: AddressLike,
    srcTokenId: BigNumberish,
    destTokenId: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    receiver: string,
    srcTokenId: bigint,
    destTokenId: bigint
  ];
  export interface OutputObject {
    owner: string;
    receiver: string;
    srcTokenId: bigint;
    destTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateTickEvent {
  export type InputTuple = [
    tick: BigNumberish,
    prev: BigNumberish,
    next: BigNumberish,
    delta: BigNumberish,
    externalFeeRate: BigNumberish,
    longDelta: BigNumberish,
    shortDelta: BigNumberish,
    counter: BigNumberish
  ];
  export type OutputTuple = [
    tick: bigint,
    prev: bigint,
    next: bigint,
    delta: bigint,
    externalFeeRate: bigint,
    longDelta: bigint,
    shortDelta: bigint,
    counter: bigint
  ];
  export interface OutputObject {
    tick: bigint;
    prev: bigint;
    next: bigint;
    delta: bigint;
    externalFeeRate: bigint;
    longDelta: bigint;
    shortDelta: bigint;
    counter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    owner: AddressLike,
    tokenId: BigNumberish,
    collateral: BigNumberish,
    longs: BigNumberish,
    shorts: BigNumberish,
    lastFeeRate: BigNumberish,
    claimableFees: BigNumberish,
    marketPrice: BigNumberish,
    liquidityRate: BigNumberish,
    currentTick: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    tokenId: bigint,
    collateral: bigint,
    longs: bigint,
    shorts: bigint,
    lastFeeRate: bigint,
    claimableFees: bigint,
    marketPrice: bigint,
    liquidityRate: bigint,
    currentTick: bigint
  ];
  export interface OutputObject {
    owner: string;
    tokenId: bigint;
    collateral: bigint;
    longs: bigint;
    shorts: bigint;
    lastFeeRate: bigint;
    claimableFees: bigint;
    marketPrice: bigint;
    liquidityRate: bigint;
    currentTick: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WriteFromEvent {
  export type InputTuple = [
    underwriter: AddressLike,
    longReceiver: AddressLike,
    taker: AddressLike,
    contractSize: BigNumberish,
    collateral: BigNumberish,
    protocolFee: BigNumberish
  ];
  export type OutputTuple = [
    underwriter: string,
    longReceiver: string,
    taker: string,
    contractSize: bigint,
    collateral: bigint,
    protocolFee: bigint
  ];
  export interface OutputObject {
    underwriter: string;
    longReceiver: string;
    taker: string;
    contractSize: bigint;
    collateral: bigint;
    protocolFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoolCore extends BaseContract {
  connect(runner?: ContractRunner | null): PoolCore;
  waitForDeployment(): Promise<this>;

  interface: PoolCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _takerFeeLowLevel: TypedContractMethod<
    [
      taker: AddressLike,
      size: BigNumberish,
      premium: BigNumberish,
      isPremiumNormalized: boolean,
      strike: BigNumberish,
      isCallPool: boolean
    ],
    [bigint],
    "view"
  >;

  annihilate: TypedContractMethod<[size: BigNumberish], [void], "nonpayable">;

  annihilateFor: TypedContractMethod<
    [account: AddressLike, size: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[p: Position.KeyStruct], [bigint], "nonpayable">;

  exercise: TypedContractMethod<
    [],
    [[bigint, bigint] & { exerciseValue: bigint; exerciseFee: bigint }],
    "nonpayable"
  >;

  exerciseFor: TypedContractMethod<
    [holders: AddressLike[], costPerHolder: BigNumberish],
    [
      [bigint[], bigint[]] & {
        exerciseValues: bigint[];
        exerciseFees: bigint[];
      }
    ],
    "nonpayable"
  >;

  getClaimableFees: TypedContractMethod<
    [p: Position.KeyStruct],
    [bigint],
    "view"
  >;

  getPoolSettings: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint, boolean] & {
        base: string;
        quote: string;
        oracleAdapter: string;
        strike: bigint;
        maturity: bigint;
        isCallPool: boolean;
      }
    ],
    "view"
  >;

  getSettlementPrice: TypedContractMethod<[], [bigint], "view">;

  getStrandedArea: TypedContractMethod<
    [],
    [[bigint, bigint] & { lower: bigint; upper: bigint }],
    "view"
  >;

  getTokenIds: TypedContractMethod<[], [bigint[]], "view">;

  marketPrice: TypedContractMethod<[], [bigint], "view">;

  settle: TypedContractMethod<[], [bigint], "nonpayable">;

  settleFor: TypedContractMethod<
    [holders: AddressLike[], costPerHolder: BigNumberish],
    [bigint[]],
    "nonpayable"
  >;

  settlePosition: TypedContractMethod<
    [p: Position.KeyStruct],
    [bigint],
    "nonpayable"
  >;

  settlePositionFor: TypedContractMethod<
    [p: Position.KeyStruct[], costPerHolder: BigNumberish],
    [bigint[]],
    "nonpayable"
  >;

  takerFee: TypedContractMethod<
    [
      taker: AddressLike,
      size: BigNumberish,
      premium: BigNumberish,
      isPremiumNormalized: boolean
    ],
    [bigint],
    "view"
  >;

  ticks: TypedContractMethod<
    [],
    [IPoolInternal.TickWithRatesStructOutput[]],
    "view"
  >;

  transferPosition: TypedContractMethod<
    [
      srcP: Position.KeyStruct,
      newOwner: AddressLike,
      newOperator: AddressLike,
      size: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  writeFrom: TypedContractMethod<
    [
      underwriter: AddressLike,
      longReceiver: AddressLike,
      size: BigNumberish,
      referrer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_takerFeeLowLevel"
  ): TypedContractMethod<
    [
      taker: AddressLike,
      size: BigNumberish,
      premium: BigNumberish,
      isPremiumNormalized: boolean,
      strike: BigNumberish,
      isCallPool: boolean
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "annihilate"
  ): TypedContractMethod<[size: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "annihilateFor"
  ): TypedContractMethod<
    [account: AddressLike, size: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[p: Position.KeyStruct], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "exercise"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { exerciseValue: bigint; exerciseFee: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exerciseFor"
  ): TypedContractMethod<
    [holders: AddressLike[], costPerHolder: BigNumberish],
    [
      [bigint[], bigint[]] & {
        exerciseValues: bigint[];
        exerciseFees: bigint[];
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaimableFees"
  ): TypedContractMethod<[p: Position.KeyStruct], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolSettings"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint, boolean] & {
        base: string;
        quote: string;
        oracleAdapter: string;
        strike: bigint;
        maturity: bigint;
        isCallPool: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSettlementPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStrandedArea"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { lower: bigint; upper: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "marketPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "settleFor"
  ): TypedContractMethod<
    [holders: AddressLike[], costPerHolder: BigNumberish],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlePosition"
  ): TypedContractMethod<[p: Position.KeyStruct], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "settlePositionFor"
  ): TypedContractMethod<
    [p: Position.KeyStruct[], costPerHolder: BigNumberish],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "takerFee"
  ): TypedContractMethod<
    [
      taker: AddressLike,
      size: BigNumberish,
      premium: BigNumberish,
      isPremiumNormalized: boolean
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ticks"
  ): TypedContractMethod<
    [],
    [IPoolInternal.TickWithRatesStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferPosition"
  ): TypedContractMethod<
    [
      srcP: Position.KeyStruct,
      newOwner: AddressLike,
      newOperator: AddressLike,
      size: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "writeFrom"
  ): TypedContractMethod<
    [
      underwriter: AddressLike,
      longReceiver: AddressLike,
      size: BigNumberish,
      referrer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Annihilate"
  ): TypedContractEvent<
    AnnihilateEvent.InputTuple,
    AnnihilateEvent.OutputTuple,
    AnnihilateEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "CancelQuoteOB"
  ): TypedContractEvent<
    CancelQuoteOBEvent.InputTuple,
    CancelQuoteOBEvent.OutputTuple,
    CancelQuoteOBEvent.OutputObject
  >;
  getEvent(
    key: "ClaimFees"
  ): TypedContractEvent<
    ClaimFeesEvent.InputTuple,
    ClaimFeesEvent.OutputTuple,
    ClaimFeesEvent.OutputObject
  >;
  getEvent(
    key: "ClaimProtocolFees"
  ): TypedContractEvent<
    ClaimProtocolFeesEvent.InputTuple,
    ClaimProtocolFeesEvent.OutputTuple,
    ClaimProtocolFeesEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Exercise"
  ): TypedContractEvent<
    ExerciseEvent.InputTuple,
    ExerciseEvent.OutputTuple,
    ExerciseEvent.OutputObject
  >;
  getEvent(
    key: "FillQuoteOB"
  ): TypedContractEvent<
    FillQuoteOBEvent.InputTuple,
    FillQuoteOBEvent.OutputTuple,
    FillQuoteOBEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoan"
  ): TypedContractEvent<
    FlashLoanEvent.InputTuple,
    FlashLoanEvent.OutputTuple,
    FlashLoanEvent.OutputObject
  >;
  getEvent(
    key: "Settle"
  ): TypedContractEvent<
    SettleEvent.InputTuple,
    SettleEvent.OutputTuple,
    SettleEvent.OutputObject
  >;
  getEvent(
    key: "SettlePosition"
  ): TypedContractEvent<
    SettlePositionEvent.InputTuple,
    SettlePositionEvent.OutputTuple,
    SettlePositionEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;
  getEvent(
    key: "TransferBatch"
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: "TransferPosition"
  ): TypedContractEvent<
    TransferPositionEvent.InputTuple,
    TransferPositionEvent.OutputTuple,
    TransferPositionEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: "UpdateTick"
  ): TypedContractEvent<
    UpdateTickEvent.InputTuple,
    UpdateTickEvent.OutputTuple,
    UpdateTickEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "WriteFrom"
  ): TypedContractEvent<
    WriteFromEvent.InputTuple,
    WriteFromEvent.OutputTuple,
    WriteFromEvent.OutputObject
  >;

  filters: {
    "Annihilate(address,uint256,uint256)": TypedContractEvent<
      AnnihilateEvent.InputTuple,
      AnnihilateEvent.OutputTuple,
      AnnihilateEvent.OutputObject
    >;
    Annihilate: TypedContractEvent<
      AnnihilateEvent.InputTuple,
      AnnihilateEvent.OutputTuple,
      AnnihilateEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "CancelQuoteOB(address,bytes32)": TypedContractEvent<
      CancelQuoteOBEvent.InputTuple,
      CancelQuoteOBEvent.OutputTuple,
      CancelQuoteOBEvent.OutputObject
    >;
    CancelQuoteOB: TypedContractEvent<
      CancelQuoteOBEvent.InputTuple,
      CancelQuoteOBEvent.OutputTuple,
      CancelQuoteOBEvent.OutputObject
    >;

    "ClaimFees(address,uint256,uint256,int256)": TypedContractEvent<
      ClaimFeesEvent.InputTuple,
      ClaimFeesEvent.OutputTuple,
      ClaimFeesEvent.OutputObject
    >;
    ClaimFees: TypedContractEvent<
      ClaimFeesEvent.InputTuple,
      ClaimFeesEvent.OutputTuple,
      ClaimFeesEvent.OutputObject
    >;

    "ClaimProtocolFees(address,uint256)": TypedContractEvent<
      ClaimProtocolFeesEvent.InputTuple,
      ClaimProtocolFeesEvent.OutputTuple,
      ClaimProtocolFeesEvent.OutputObject
    >;
    ClaimProtocolFees: TypedContractEvent<
      ClaimProtocolFeesEvent.InputTuple,
      ClaimProtocolFeesEvent.OutputTuple,
      ClaimProtocolFeesEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256,uint256,uint256,int256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Exercise(address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ExerciseEvent.InputTuple,
      ExerciseEvent.OutputTuple,
      ExerciseEvent.OutputObject
    >;
    Exercise: TypedContractEvent<
      ExerciseEvent.InputTuple,
      ExerciseEvent.OutputTuple,
      ExerciseEvent.OutputObject
    >;

    "FillQuoteOB(bytes32,address,address,uint256,tuple,tuple,uint256,uint256,uint256,bool)": TypedContractEvent<
      FillQuoteOBEvent.InputTuple,
      FillQuoteOBEvent.OutputTuple,
      FillQuoteOBEvent.OutputObject
    >;
    FillQuoteOB: TypedContractEvent<
      FillQuoteOBEvent.InputTuple,
      FillQuoteOBEvent.OutputTuple,
      FillQuoteOBEvent.OutputObject
    >;

    "FlashLoan(address,address,uint256,uint256)": TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;
    FlashLoan: TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;

    "Settle(address,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SettleEvent.InputTuple,
      SettleEvent.OutputTuple,
      SettleEvent.OutputObject
    >;
    Settle: TypedContractEvent<
      SettleEvent.InputTuple,
      SettleEvent.OutputTuple,
      SettleEvent.OutputObject
    >;

    "SettlePosition(address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SettlePositionEvent.InputTuple,
      SettlePositionEvent.OutputTuple,
      SettlePositionEvent.OutputObject
    >;
    SettlePosition: TypedContractEvent<
      SettlePositionEvent.InputTuple,
      SettlePositionEvent.OutputTuple,
      SettlePositionEvent.OutputObject
    >;

    "Trade(address,uint256,tuple,uint256,uint256,uint256,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;

    "TransferBatch(address,address,address,uint256[],uint256[])": TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    "TransferPosition(address,address,uint256,uint256)": TypedContractEvent<
      TransferPositionEvent.InputTuple,
      TransferPositionEvent.OutputTuple,
      TransferPositionEvent.OutputObject
    >;
    TransferPosition: TypedContractEvent<
      TransferPositionEvent.InputTuple,
      TransferPositionEvent.OutputTuple,
      TransferPositionEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    "UpdateTick(uint256,uint256,uint256,int256,uint256,int256,int256,uint256)": TypedContractEvent<
      UpdateTickEvent.InputTuple,
      UpdateTickEvent.OutputTuple,
      UpdateTickEvent.OutputObject
    >;
    UpdateTick: TypedContractEvent<
      UpdateTickEvent.InputTuple,
      UpdateTickEvent.OutputTuple,
      UpdateTickEvent.OutputObject
    >;

    "Withdrawal(address,uint256,uint256,uint256,uint256,int256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "WriteFrom(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      WriteFromEvent.InputTuple,
      WriteFromEvent.OutputTuple,
      WriteFromEvent.OutputObject
    >;
    WriteFrom: TypedContractEvent<
      WriteFromEvent.InputTuple,
      WriteFromEvent.OutputTuple,
      WriteFromEvent.OutputObject
    >;
  };
}
