/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReentrancyGuardExtendedInterface extends Interface {
  getFunction(
    nameOrSignature: "__staticCallCheck" | "setReentrancyGuardDisabled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReentrancyStaticCallCheck"
      | "SetReentrancyGuardDisabled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "__staticCallCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReentrancyGuardDisabled",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "__staticCallCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReentrancyGuardDisabled",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReentrancyStaticCallCheckEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetReentrancyGuardDisabledEvent {
  export type InputTuple = [disabled: boolean];
  export type OutputTuple = [disabled: boolean];
  export interface OutputObject {
    disabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReentrancyGuardExtended extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrancyGuardExtended;
  waitForDeployment(): Promise<this>;

  interface: ReentrancyGuardExtendedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  __staticCallCheck: TypedContractMethod<[], [void], "nonpayable">;

  setReentrancyGuardDisabled: TypedContractMethod<
    [disabled: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "__staticCallCheck"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReentrancyGuardDisabled"
  ): TypedContractMethod<[disabled: boolean], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReentrancyStaticCallCheck"
  ): TypedContractEvent<
    ReentrancyStaticCallCheckEvent.InputTuple,
    ReentrancyStaticCallCheckEvent.OutputTuple,
    ReentrancyStaticCallCheckEvent.OutputObject
  >;
  getEvent(
    key: "SetReentrancyGuardDisabled"
  ): TypedContractEvent<
    SetReentrancyGuardDisabledEvent.InputTuple,
    SetReentrancyGuardDisabledEvent.OutputTuple,
    SetReentrancyGuardDisabledEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReentrancyStaticCallCheck()": TypedContractEvent<
      ReentrancyStaticCallCheckEvent.InputTuple,
      ReentrancyStaticCallCheckEvent.OutputTuple,
      ReentrancyStaticCallCheckEvent.OutputObject
    >;
    ReentrancyStaticCallCheck: TypedContractEvent<
      ReentrancyStaticCallCheckEvent.InputTuple,
      ReentrancyStaticCallCheckEvent.OutputTuple,
      ReentrancyStaticCallCheckEvent.OutputObject
    >;

    "SetReentrancyGuardDisabled(bool)": TypedContractEvent<
      SetReentrancyGuardDisabledEvent.InputTuple,
      SetReentrancyGuardDisabledEvent.OutputTuple,
      SetReentrancyGuardDisabledEvent.OutputObject
    >;
    SetReentrancyGuardDisabled: TypedContractEvent<
      SetReentrancyGuardDisabledEvent.InputTuple,
      SetReentrancyGuardDisabledEvent.OutputTuple,
      SetReentrancyGuardDisabledEvent.OutputObject
    >;
  };
}
