#!/bin/bash
# To be able to run this on Windows : npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"

# Exit on first error
set -e

# Delete stale directories if they exists
rm -rf ./temp
rm -rf ./abi
rm -rf ./deployment
rm -rf ./dist
rm -rf ./typechain

# Clone the repo and install dependencies
git clone -b master https://github.com/Premian-Labs/premia-v3-contracts-private.git ./temp
cd temp
yarn install
forge install

# Build and copy the contracts
forge build --extra-output-files abi
cd ..
ts-node ./utils/copyAbi.ts

# Copy the deployment files
mkdir ./deployment
cp -r ./temp/deployments/arbitrum/metadata.json ./deployment/arbitrum.json
cp -r ./temp/deployments/arbitrumGoerli/metadata.json ./deployment/arbitrumGoerli.json
cp -r ./temp/deployments/arbitrumNova/metadata.json ./deployment/arbitrumNova.json
cp -r ./temp/scripts/utils/types.deployment.ts ./deployment/types.ts

echo "/* Autogenerated file. Do not edit manually. */" >> ./deployment/index.ts
echo "import {ContractDeploymentMetadata, DeploymentMetadata} from './types';" >> ./deployment/index.ts
echo "import arbitrumMetadata from './arbitrum.json';" >> ./deployment/index.ts
echo "import arbitrumGoerliMetadata from './arbitrumGoerli.json';" >> ./deployment/index.ts
echo "import arbitrumNovaMetadata from './arbitrumNova.json';" >> ./deployment/index.ts
echo "export { ContractDeploymentMetadata, ContractKey, ContractType,  DeploymentMetadata } from './types';" >> ./deployment/index.ts
echo "export const arbitrum = arbitrumMetadata as DeploymentMetadata;" >> ./deployment/index.ts
echo "export const arbitrumGoerli = arbitrumGoerliMetadata as DeploymentMetadata;" >> ./deployment/index.ts
echo "export const arbitrumNova = arbitrumNovaMetadata as { core: { [key: string]: ContractDeploymentMetadata } };" >> ./deployment/index.ts

# Generate the typechain files
yarn codegen

# Compile and generate build files
tsc